plugins = [
    "Duckonaut/split-monitor-workspaces",
    "zakk4223/hyprNStack",
    "zakk4223/hyprRiver",
    "VortexCoyote/hyprfocus",
    "ItsDrike/hyprland-dwindle-autogroup",
    "outfoxxed/hy3",
    "horriblename/hyprland-touch-gestures",
    "Duckonaut/split-monitor-workspaces",
]
