config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  d_oh-my-zsh:
    src: oh-my-zsh
    dst: ~/.oh-my-zsh
    chmod: '751'
  d_applications:
    src: local/share/applications
    dst: ~/.local/share/applications
profiles:
  penguin:
    dotfiles:
    - f_zshrc
    - d_oh-my-zsh
    - d_applications
