config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  d_hypr:
    src: config/hypr
    dst: ~/.config/hypr
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
  d_wofi:
    src: config/wofi
    dst: ~/.config/wofi
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  d_swaylock:
    src: config/swaylock
    dst: ~/.config/swaylock
  d_sddm.conf.d:
    src: etc/sddm.conf.d
    dst: /etc/sddm.conf.d
  f_pacman.conf:
    src: etc/pacman.conf
    dst: /etc/pacman.conf
  f_mirrorlist:
    src: etc/pacman.d/mirrorlist
    dst: /etc/pacman.d/mirrorlist
  f_backlight.rules:
    src: etc/udev/rules.d/backlight.rules
    dst: /etc/udev/rules.d/backlight.rules
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
profiles:
  arch-hyprland:
    dotfiles:
    - f_zshrc
    - d_hypr
    - d_waybar
    - d_wofi
    - d_kitty
    - d_dunst
    - d_swaylock
    - d_sddm.conf.d
    - f_pacman.conf
    - f_mirrorlist
    - f_backlight.rules
    - d_nvim
